version: 2
jobs:
  build:
    working_directory: ~/circleci-java-exactify

    docker:
      - image: circleci/openjdk:9-jdk-browsers

    steps:
      - checkout
      - restore_cache:
          key: circleci-java-exactify-{{ checksum "build.gradle" }}
      
      - run: ./gradle 
      
      - save_cache:
          paths:
            - ~/.gradlew shadowJar
          key: circleci-java-exactify-{{ checksum "build.gradle" }}
      
      - run: ./gradlew test
      
      - store_test_results:
          path: build/reports/tests/test
      
      - store_artifacts:
          path: build/libs
