version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
    - image: circleci/openjdk:9-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: gradle shadowJar

    - run: mkdir -p artifacts/temp
    - run:
        name: "Save version"
        command: grep -e '^version' build.gradle | cut -d ' ' -f 2 | tr -d "'" > artifacts/temp/version.txt

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - store_artifacts:
        path: build/libs

    - run: cp build/libs/*.jar artifacts/
    - run: gradle test

    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/html
          find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} ~/junit/ \;
          cp -r build/reports/tests/test/* ~/junit/html/
        when: always

    - store_test_results:
        path: ~/junit

    - store_artifacts:
        path: ~/junit

    - persist_to_workspace:
        root: artifacts
        paths:
        - ./*.jar
        - temp/version.txt

  publish-github-release:
    docker:
    - image: cibuilds/github:0.10
    steps:
    - attach_workspace:
        at: ./artifacts
    - run:
        name: "Publish Release on GitHub"
        command: |
          VERSION=$(cat ./artifacts/temp/version.txt)
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
  release:
    jobs:
    - build:
        filters:
          tags:
            only: /^\d+\.\d+\.\d+$/
    - publish-github-release:
        requires:
        - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^\d+\.\d+\.\d+$/